theme: jekyll-theme-minimal
title: Julie Ngo Tran
baseurl: "/myportfolio"  
description: |
  Business Analytics : Data Cleaning , Data Modeling , Forecasting

  <br><br>
  
  <a href="www.linkedin.com/in/julie-ngo-tran-110560220" target="_blank"
     style="display:block; text-align:center; padding:8px; margin-bottom:8px;
     background:#0077b5; color:white; border-radius:6px; text-decoration:none;">
     LinkedIn
  </a>
  
  <a href="mailto:frjulie8@bu.edu"
     style="display:block; text-align:center; padding:8px;
     background:#333; color:white; border-radius:6px; text-decoration:none;">
     Email
  </a>

show_downloads: false

github:
  is_project_page: false
