theme: jekyll-theme-minimal
title: Julie Ngo Tran
description: Business Analytics | Data Cleaning | Decision Modeling | Forecasting 

show_downloads: false

github:
  is_project_page: false

linkedin: https://linkedin.com/in/your-link
email: yourname@email.com
